export { default as Header } from "./Header";
export { default as Home } from "./Home";
export { default as Gallery } from "./Gallery";
export { default as About } from "./About";
export { default as Services } from "./Services";
export { default as Rooms } from "./Rooms";
export { default as Contact } from "./Contact";
export { default as Signin } from "./Signin";
export { default as Signup } from "./Signup";
